version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse_for_airflow
    restart: on-failure
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-default}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./init_ch.sql:/docker-entrypoint-initdb.d/init_ch.sql
      - clickhouse-for-airflow-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse-for-airflow-data:
    name: clickhouse-for-airflow-data
  
networks:
  default:
    name: airflow_network
    external: true
